# # config file version
# apiVersion: 1

# # list of datasources to insert/update
# # available in the database
# datasources:
#   - name: PostgreSQL
#     type: postgres
#     access: proxy
#     url: db.:5432
#     database: test
#     user: postgres
#     secureJsonData:
#       password: 'example'
#     jsonData:
#       sslmode: 'disable'

# config file version
apiVersion: 1

# list of datasources to insert/update
# available in the database
datasources:
  - name: MonitoringPostgreSQL
    type: postgres
    url: db.:5432
    user: postgres
    secureJsonData:
      password: 'example'
    jsonData:
      database: test
      sslmode: 'disable'
